export const OHIO_STATE_RATE = 5.75;

export interface OhioCountyTax {
  county: string;
  countyRate: number;   // county permissive rate %
  transitRate: number;  // transit rate % (0 if N/A)
  totalRate: number;
}

export const OHIO_COUNTY_TAX: OhioCountyTax[] = [
  { county: 'Adams',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Allen',       countyRate: 1.00, transitRate: 0.10, totalRate: 6.85 },
  { county: 'Ashland',     countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Ashtabula',   countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Athens',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Auglaize',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Belmont',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Brown',       countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Butler',      countyRate: 0.75, transitRate: 0,    totalRate: 6.50 },
  { county: 'Carroll',     countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Champaign',   countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Clark',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Clermont',    countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Clinton',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Columbiana',  countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Coshocton',   countyRate: 2.00, transitRate: 0,    totalRate: 7.75 },
  { county: 'Crawford',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Cuyahoga',    countyRate: 1.25, transitRate: 1.00, totalRate: 8.00 },
  { county: 'Darke',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Defiance',    countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Delaware',    countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Erie',        countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Fairfield',   countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Fayette',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Franklin',    countyRate: 1.25, transitRate: 1.00, totalRate: 8.00 },
  { county: 'Fulton',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Gallia',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Geauga',      countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Greene',      countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Guernsey',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Hamilton',    countyRate: 1.25, transitRate: 0.80, totalRate: 7.80 },
  { county: 'Hancock',     countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Hardin',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Harrison',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Henry',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Highland',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Hocking',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Holmes',      countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Huron',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Jackson',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Jefferson',   countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Knox',        countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Lake',        countyRate: 1.00, transitRate: 0.50, totalRate: 7.25 },
  { county: 'Lawrence',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Licking',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Logan',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Lorain',      countyRate: 0.75, transitRate: 0,    totalRate: 6.50 },
  { county: 'Lucas',       countyRate: 1.50, transitRate: 0.50, totalRate: 7.75 },
  { county: 'Madison',     countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Mahoning',    countyRate: 1.50, transitRate: 0.25, totalRate: 7.50 },
  { county: 'Marion',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Medina',      countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Meigs',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Mercer',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Miami',       countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Monroe',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Montgomery',  countyRate: 1.25, transitRate: 0.50, totalRate: 7.50 },
  { county: 'Morgan',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Morrow',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Muskingum',   countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Noble',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Ottawa',      countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Paulding',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Perry',       countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Pickaway',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Pike',        countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Portage',     countyRate: 1.00, transitRate: 0.25, totalRate: 7.00 },
  { county: 'Preble',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Putnam',      countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Richland',    countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Ross',        countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Sandusky',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Scioto',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Seneca',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Shelby',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Stark',       countyRate: 0.50, transitRate: 0.25, totalRate: 6.50 },
  { county: 'Summit',      countyRate: 0.50, transitRate: 0.50, totalRate: 6.75 },
  { county: 'Trumbull',    countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Tuscarawas',  countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Union',       countyRate: 1.25, transitRate: 0,    totalRate: 7.00 },
  { county: 'Van Wert',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Vinton',      countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Warren',      countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Washington',  countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Wayne',       countyRate: 0.75, transitRate: 0,    totalRate: 6.50 },
  { county: 'Williams',    countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
  { county: 'Wood',        countyRate: 1.00, transitRate: 0,    totalRate: 6.75 },
  { county: 'Wyandot',     countyRate: 1.50, transitRate: 0,    totalRate: 7.25 },
];

export const ohioCountyMap = Object.fromEntries(
  OHIO_COUNTY_TAX.map(c => [c.county.toLowerCase(), c])
);
